### ISSUE TITLE
Neue Model-Klasse "Box"

### ISSUE THREAD

**Issue by StormyCode** [StormyCode/ScanExpert#1]
Diese Klasse beinhaltet alle Informationen über einen einzelnen Tabelleneintrag.

**Comment by haayhappen** [comment]
Neue Klasse erstellt: ``class Box``
Klassenvariablen erstellt
Konstruktor angelegt(für DataRow)

**Comment by StormyCode** [comment]
![image](https://cloud.githubusercontent.com/assets/11949160/11467919/c30a8c36-974b-11e5-9a86-8e39dadeae21.png)

Klassenvariablen müssen noch in ``Properties`` umgewandelt werden. Guck mal nach, wie wir es in dem Projekt ``Wareneingangstool`` gemacht hatten.

**Comment by haayhappen** [comment]
Properties hinzugefügt
