### ISSUE TITLE
Neue Controller-Klasse "Stock"

### ISSUE THREAD

**Issue by StormyCode** [StormyCode/ScanExpert#2]
Diese Klasse beinhaltet eine Liste aller ``Box`` Objekte.

**Comment by haayhappen** [comment]
Neue Klasse angelegt: ``class Stock``
Konstruktor angelegt: ``private Stock()``
Methoden angelegt:``GetInstance()``,``UpdateBoxes()``,``GetDisplayData()``,
``ManipulateDB(ScanExpertNew.Box b, ManipulationType type)``.
