### ISSUE TITLE
Erstellen der GUI

### ISSUE THREAD

**Issue by StormyCode** [StormyCode/ScanExpert#3]
Die GUI hat an der Oberfläche der Vorgängerversion zu ähneln/gleichen. Über einzelne Details kann natürlich diskutiert werden. Denkt dran, Aussehen ist nicht alles. Es kommt auf die inneren Werte an! ^^

**Comment by llatinoo** [comment]
``MetroFramework.dll`` hinzugefügt

**Comment by llatinoo** [comment]
ScanExpert Frame-Reiter :
<kbd>Tabelle</kbd> <kbd>Add</kbd> <kbd>Edit</kbd> <kbd>Details</kbd> <kbd>Deliverer</kbd><kbd>Show Delivered</kbd> <kbd>Search</kbd>

<kbd>Tabelle</kbd> Beinhaltet die Tabelle mit den Paketen

Die Restlichen Fenster übernehmen die Funktionen des Vorgängers

**Comment by llatinoo** [comment]
Some formal changes

**Comment by StormyCode** [comment]
<kbd>Edit</kbd> und <kbd>Details</kbd> sollen künftig unter demselben Tab verfügbar sein.
