### ISSUE TITLE
Klassen zur Datenbankverbindung erstellen

### ISSUE THREAD

**Issue by StormyCode** [StormyCode/ScanExpert#5]
Über diese Klassen wird eine Datenbankverbindung hergestellt.
Die Verbindungsparameter wie z.B. der ``connectionString`` müssen in das externe ``Settingsfile``  ausgelagert werden!

**Comment by haayhappen** [comment]
Klassen die zur Datenbankverbindung benötigt werden hinzugefügt.
``Controller_DatabaseConnection``
``Controller_Network``
``Model_DatabaseActions``
``Model_DatabaseConnections``

**Comment by StormyCode** [comment]
Verschieben von ``Model`` Klassen in den entsprechenden Projektordner.
Verschieben von ``Controller`` Klassen in den entsprechenden Projektordner.
Umbenennen der Klassen (entfernen von "Model_" und "Controller_" aus den Dateinamen)
Anpassung der ``namespaces``.
Hinzufügen der entsprechenden ``usings``

**Comment by StormyCode** [comment]
Ändern von ``SqlConnection`` Klassenvariable zu Property

**Comment by StormyCode** [comment]
Ich habe den ConnectionString, der harcoded gewesen ist, herausgenommen. Er ist über den ``SettingsHandler`` jetzt abrufbar unter dem Namen ``connectionstring``!

**Comment by StormyCode** [comment]
Habe die Name aller Methoden der Klasse ``DatabaseAction`` an die C# Konvention zur Namensgebung angepasst

**Comment by haayhappen** [comment]
Interface ``IDisposable`` hinzugefügt
Methode ``Dispose()``mit ``Connection.Close()`` hinzugefügt
